version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /app/ynetd -u appuser -d /app -p 3333 -lt 2 "bash -c 'echo New connection... 1>&2' && /app/main"
    ports:
      - 2312:3333
    restart: always
    volumes:
      - ./hof.txt:/app/hof.txt
