version: "3.9"

services:
  server:
    build:
      context: ./chat
      dockerfile: Dockerfile
    # ports:
    #   - "8005:5000"
    command: /usr/bin/python3 app.py
    # environment:
    #   - DEBUG=True
    # volumes:
    #   - ./chat:/app
    restart: always

  waf:
    image: owasp/modsecurity-crs:3.3.2-nginx
    ports:
      - 2309:80
    depends_on:
      - server
    environment:
      - SERVERNAME=localhost
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - PROXY=1
      - BACKEND=http://server:5000
      - LOGLEVEL=info
    volumes:
      - ./REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
      - ./RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: 202107_backend
    user: appuser
    working_dir: /app
    entrypoint: python3 -u app.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
